app:
  name: ubuntu-mate
  capname: Ubuntu-Mate

image:
  repository: lscr.io/linuxserver/webtop:ubuntu-mate
  tag: latest
  policy: Always

env:
  UID: 99
  GID: 100
  TZ: "America/Chicago"
  CUSTOM_USER: "brimdor"
  TITLE: "UBUNTU-MATE"
  START_DOCKER: "true"
  DISABLE_IPV6: "true"

ingress:
  name: ubuntu-mate-ingress
  host: ubuntu-mate.eaglepass.io

service:
  port: 3000

opSecret:
  PASSWORD:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "qvocwbnbqwlpsakd6tu5onhsui"
    secretName: "password"
    key: "password"