app-template:
  global:
    alwaysAppendIdentifierToResourceName: false
  controllers:
    main:
      forceRename: tamalotl-canary
      type: deployment
      replicas: 1
      strategy: RollingUpdate
      pod:
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          fsGroup: 101
          seccompProfile: {type: RuntimeDefault}
      containers:
        web:
          image:
            repository: 10.0.20.11:32309/tamalotl
            tag: canary-1688747c53caf8c7a1f987e0c5eaadd193275791
            digest: sha256:d88d9433a59d90addcd655708d2371cee079b9aeba585035bc111b8111e4f792
            pullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {cpu: 25m, memory: 32Mi}
            limits: {cpu: 500m, memory: 128Mi}
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet: {path: /healthz, port: http}
                periodSeconds: 20
                timeoutSeconds: 3
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet: {path: /healthz, port: http}
                periodSeconds: 5
                timeoutSeconds: 3
            startup:
              enabled: true
              custom: true
              spec:
                httpGet: {path: /healthz, port: http}
                periodSeconds: 2
                failureThreshold: 30
  service:
    main:
      forceRename: tamalotl-canary
      controller: main
      ports:
        http: {port: 80, protocol: HTTP, targetPort: http}
  ingress:
    main:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: tamalotl-canary.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service: {identifier: main, port: http}
      tls:
        - hosts: [tamalotl-canary.eaglepass.io]
          secretName: tamalotl-canary-tls
  persistence:
    temp:
      type: emptyDir
      sizeLimit: 16Mi
      globalMounts:
        - path: /tmp
  networkpolicies:
    main:
      controller: main
      policyTypes: [Ingress, Egress]
      rules:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels: {kubernetes.io/metadata.name: ingress-nginx}
            ports:
              - {protocol: TCP, port: 8080}
        egress: []
