apiVersion: v2
name: qdrant
description: A Helm chart for deploying Qdrant vector database using bjw-s app-template
type: application
version: 1.0.0
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
    alias: app-template
