apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.DISCORD_TOKEN.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.DISCORD_TOKEN.vault }}/items/{{ .Values.opSecret.DISCORD_TOKEN.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.EMBY_API.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.EMBY_API.vault }}/items/{{ .Values.opSecret.EMBY_API.item }}"