apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
        - name: mail-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          volumeMounts:
            {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          nfs:
            server: "{{ .Values.nfs.server }}"
            path: {{ .nfsPath }}
        {{- end }}
      resources:
        requests:
          memory: "{{ .Values.resources.requests.memory }}"
          cpu: "{{ .Values.resources.requests.cpu }}"
        limits:
          memory: "{{ .Values.resources.limits.memory }}"
          cpu: "{{ .Values.resources.limits.cpu }}"
