apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
        - name: mail-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 25
              name: smtp
            - containerPort: 465
              name: smtps
            - containerPort: 587
              name: submission
            - containerPort: 143
              name: imap
            - containerPort: 993
              name: imaps
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: mail-data
              mountPath: /var/mail
            - name: mail-state
              mountPath: /var/mail-state
            - name: mail-logs
              mountPath: /var/log/mail
            - name: mail-config
              mountPath: /tmp/docker-mailserver
      volumes:
        - name: mail-data
          persistentVolumeClaim:
            claimName: mail-data-pvc
        - name: mail-state
          persistentVolumeClaim:
            claimName: mail-state-pvc
        - name: mail-logs
          persistentVolumeClaim:
            claimName: mail-logs-pvc
        - name: mail-config
          persistentVolumeClaim:
            claimName: mail-config-pvc
