apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
        - name: mail-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          volumeMounts:
            - name: mail-data
              mountPath: {{ .Values.volumes.mailData.mountPath }}
            - name: mail-state
              mountPath: {{ .Values.volumes.mailState.mountPath }}
            - name: mail-logs
              mountPath: {{ .Values.volumes.mailLogs.mountPath }}
            - name: mail-config
              mountPath: {{ .Values.volumes.mailConfig.mountPath }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
      volumes:
        - name: mail-data
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.volumes.mailData.nfsPath }}
        - name: mail-state
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.volumes.mailState.nfsPath }}
        - name: mail-logs
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.volumes.mailLogs.nfsPath }}
        - name: mail-config
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.volumes.mailConfig.nfsPath }}
