apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}/mail-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-state-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}/mail-state

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}/mail-logs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}/mail-config
