apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.mail-data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-state-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.mail-state.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.mail-logs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.mail-config.size }}
