app-template:
  controllers:
    main:
      containers:
        database:
          image:
            repository: docker.io/brimdor/backlog_database
            tag: latest
        backend:
          image:
            repository: docker.io/brimdor/backlog_backend
            tag: latest
          env:
            HOST_URL: https://backlog.eaglepass.io
            CORS_ORIGIN: https://backlog.eaglepass.io
            DB_HOST: localhost
            DB_PORT: 3306
            DB_USER:
              vault: "4uaua4a45yuhnwhehp5bwylmti"
              item: "3g3cuf6gowcxdhtlteivplc27u"
              secretName: "mysql-user"
              key: "db_user"
            DB_PASSWORD:
              vault: "4uaua4a45yuhnwhehp5bwylmti"
              item: "3g3cuf6gowcxdhtlteivplc27u"
              secretName: "mysql-password"
              key: "db_password"
        frontend:
          image:
            repository: docker.io/brimdor/backlog_frontend
            tag: latest
          env:
            REACT_APP_API_BASE_URL: http://localhost:3000
            REACT_APP_THEME: dark
  service:
    database:
      ports:
        http:
          port: 3600
          protocol: HTTP
    backend:
      ports:
        http:
          port: 3000
          protocol: HTTP
    frontend:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    frontend:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: backlog.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: frontend
                port: http
      tls:
        - hosts:
            - backlog.eaglepass.io
          secretName: backlog-companion-tls
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 150Gi
      advancedMounts:
        main:
          main:
            - path: /root/.ollama
    ui:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        ui:
          main:
            - path: /app/backend/data
          backup:
            - path: /app/backend/data
          restore:
            - path: /app/backend/data
    nfs:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/ollama-ui
      advancedMounts:
        ui:
          backup:
            - path: /mnt/backup
          restore:
            - path: /mnt/backup
