# values for umbrella/parent chart to render LiveKit server
# This file provides both an `app-template` mapping (used by many apps in this repo)
# and a top-level `livekit` mapping for umbrella charts that reference the upstream
# livekit chart values directly.

replicaCount: 1

app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/livekit/livekit-server
            tag: "v1.5.2"
            pullPolicy: IfNotPresent
          env:
            LIVEKIT_LOG_LEVEL: "info"
            LIVEKIT_REGION: "local"
      extraContainers: {}
  service:
    main:
      controller: main
      primary: true
      ports:
        grpc:
          port: 7880
          protocol: TCP
        http:
          port: 7881
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: livekit.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - livekit.eaglepass.io
          secretName: livekit-eaglepass-io-tls

  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        main:
          main:
            - path: /data

  nodeSelector: {}
  tolerations: []
  affinity: {}

# Redis sidecar settings (some umbrella templates expect `sidecars.redis` or `redis`)
redis:
  enabled: true
  # If umbrella expects a list under extraContainers/sidecars, it can map from this
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  port: 6379
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

# Direct upstream-style livekit values (kept small and safe for local testing)
livekit:
  image:
    repository: ghcr.io/livekit/livekit-server
    tag: "v1.5.2"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    enabled: true
    type: ClusterIP
    port: 7881
    targetPort: 7881
    annotations: {}
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: livekit.eaglepass.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: livekit-eaglepass-io-tls
        hosts:
          - livekit.eaglepass.io
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 5Gi
    mountPath: /data
  redis:
    sidecar:
      enabled: true
      image:
        repository: redis
        tag: "7-alpine"
        pullPolicy: IfNotPresent
      port: 6379
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  nodeSelector: {}
  tolerations: []
  affinity: {}
