app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/vscode-tunnel
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            TUNNEL_NAME: "SecretTunnel"
            PROVIDER: "microsoft"
            DOCKER_HOST: ssh://root@10.0.50.3
            DOCKER: "true"
            PRIVATE_KEY: "true"
            SSH_PRIVATE:
              valueFrom:
                secretKeyRef:
                  name: "private-key"
                  key: "private-key"
            SSH_PUBLIC:
              valueFrom:
                secretKeyRef:
                  name: "public-key"
                  key: "public-key"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      enabled: false
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 15Gi
      advancedMounts:
        main:
          main:
            - path: /home/coder
    podman:
      type: hostPath
      hostPath: /run/podman/podman.sock
      advancedMounts:
        main:
          main:
            - path: /run/podman/podman.sock
    docker:
      type: hostPath
      hostPath: /var/run/docker.sock
      advancedMounts:
        main:
          main:
            - path: /var/run/docker.sock

  defaultPodOptions:
    hostname: "static"
    securityContext:
      fsGroup: 1000

secrets:
  SSH_PRIVATE:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "72o4yiye3zrgz3tiucrdgjgpqq"
    secretName: "private-key"
  SSH_PUBLIC:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "72o4yiye3zrgz3tiucrdgjgpqq"
    secretName: "public-key"