app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/vscode-tunnel
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            TUNNEL_NAME: "SecretTunnel"
            PROVIDER: "microsoft"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      enabled: false
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 15Gi
      advancedMounts:
        main:
          main:
            - path: /home/coder
    podman:
      type: hostPath
      hostPath: /run/podman/podman.sock
      advancedMounts:
        main:
          main:
            - path: /run/podman/podman.sock
    docker:
      type: hostPath
      hostPath: /var/run/docker.sock
      advancedMounts:
        main:
          main:
            - path: /var/run/docker.sock

  defaultPodOptions:
    hostname: "static"
    securityContext:
      fsGroup: 1000