app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/vscode-tunnel
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            TUNNEL_NAME: "SecretTunnel"
            PROVIDER: "microsoft"
            DOCKER_HOST: ssh://root@10.0.50.3
            SSH_PRIVATE:
              valueFrom:
                secretKeyRef:
                  name: "private-key"
                  key: "private-key"
            SSH_PUBLIC:
              valueFrom:
                secretKeyRef:
                  name: "public-key"
                  key: "public-key"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      enabled: false
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 15Gi
      advancedMounts:
        main:
          main:
            - path: /home/coder

  defaultPodOptions:
    hostname: "static"
    securityContext:
      fsGroup: 1000

opSecrets:
  SSH_PRIVATE:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "72o4yiye3zrgz3tiucrdgjgpqq"
    secretName: "private-key"
  SSH_PUBLIC:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "72o4yiye3zrgz3tiucrdgjgpqq"
    secretName: "public-key"