# Supabase subchart configuration
supabase:
  # Database configuration
  db:
    enabled: true
    image:
      tag: "15.1.0.147"
    persistence:
      enabled: true
      size: 20Gi
      storageClass: ""
    
  # Kong API Gateway
  kong:
    enabled: true
    image:
      tag: "2.8.1"
    service:
      type: ClusterIP
      port: 8000
    ingress:
      enabled: false  # We'll handle ingress separately
    
  # Supabase Studio
  studio:
    enabled: true
    image:
      tag: "20240422-5cf8f30"
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: false  # We'll handle ingress separately
    
  # Auth service
  auth:
    enabled: true
    image:
      tag: "v2.143.0"
    
  # REST API
  rest:
    enabled: true
    image:
      tag: "v12.0.1"
    
  # Realtime service
  realtime:
    enabled: true
    image:
      tag: "v2.25.50"
    
  # Storage service
  storage:
    enabled: true
    image:
      tag: "v0.46.4"
    
  # Meta service
  meta:
    enabled: true
    image:
      tag: "v0.80.0"

# Global configuration with 1Password operator integration
global:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
    annotations:
      operator.1password.io/item-path: "vaults/homelab/items/supabase-secrets"
      operator.1password.io/item-name: "supabase-secrets"

# Ingress configuration
ingress:
  enabled: true
  className: "kong"
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "true"
  
  # Supabase API ingress
  api:
    enabled: true
    host: supabase.eaglepass.io
    tls:
      enabled: true
      secretName: supabase-tls
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: supabase-kong
            port: 8000
  
  # Supabase Studio ingress  
  studio:
    enabled: true
    host: studio.eaglepass.io
    tls:
      enabled: true
      secretName: studio-tls
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: supabase-studio
            port: 3000

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  annotations: {}

# Service configuration
service:
  kong:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  
  studio:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  
  db:
    type: ClusterIP
    port: 5432
    targetPort: 5432

# Environment variables with 1Password operator integration
env:
  # Database configuration
  POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "postgres-password"
  
  # JWT secrets
  JWT_SECRET:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets" 
        key: "jwt-secret"
  
  ANON_KEY:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "anon-key"
  
  SERVICE_ROLE_KEY:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "service-role-key"
  
  # Supabase configuration
  SUPABASE_URL:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "supabase-url"
  
  SUPABASE_ANON_KEY:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "supabase-anon-key"
  
  # Studio configuration
  STUDIO_DEFAULT_ORGANIZATION:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "studio-default-organization"
  
  STUDIO_DEFAULT_PROJECT:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "studio-default-project"
  
  # Storage configuration
  GLOBAL_S3_BUCKET:
    valueFrom:
      secretKeyRef:
        name: "supabase-secrets"
        key: "storage-s3-bucket"

# Additional configuration for subchart override
supabaseOverride:
  # Environment variables that will be passed to all Supabase services
  envVars:
    SUPABASE_PUBLIC_URL: "https://supabase.eaglepass.io"
    SUPABASE_URL: "https://supabase.eaglepass.io"
    API_EXTERNAL_URL: "https://supabase.eaglepass.io"
    STUDIO_URL: "https://studio.eaglepass.io"
    
  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
