# https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
open-webui:
  ollama:
    ollama:
      models:
        pull:
          - deepseek-coder:6.7b
          - deepseek-r1:8b
    runtimeClassName: nvidia
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: &ollamahost ollama-canary.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ollama-tls
          hosts:
            - *ollamahost
    extraEnv:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "all"
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "all"
    persistentVolume:
      enabled: true
      size: 100Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: In
                values:
                  - "true"
  ingress:
    enabled: true
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: &openwebuihost ai-canary.eaglepass.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: openwebui-tls
        hosts:
          - *openwebuihost
  extraEnvVars:
    - name: ENABLE_LOGIN_FORM
      value: "true"
    - name: WEBUI_URL
      value: *openwebuihost
    - name: BYPASS_MODEL_ACCESS_CONTROL
      value: "true"