apiVersion: v2
name: pigeon-pod
description: A Helm chart for deploying PigeonPod using bjw-s common chart
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts