apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea-actions-runner.fullname" . }}-config
  labels:
    {{- include "gitea-actions-runner.labels" . | nindent 4 }}
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: .runner
      capacity: 1
      envs:
        A_RUNNER_NAME: {{ .Values.gitea.name | quote }}
      timeout: 0s
    container:
      network_mode: bridge
      privileged: false
      valid_volumes:
        - /var/run/docker.sock:/var/run/docker.sock
