{{- if not .Values.existingTokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-actions-runner.fullname" . }}-token
  labels:
    {{- include "gitea-actions-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.gitea.runnerToken | quote }}
{{- end }}
