apiVersion: apps/v1
kind: Deployment
metadata:
  name: sporecast-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sporecast-frontend
  template:
    metadata:
      labels:
        app: sporecast-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
