apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sporecast
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: sporecast-canary.eaglepass.io
    external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sporecast-canary.eaglepass.io
      secretName: sporecast-canary-tls
  rules:
    - host: sporecast-canary.eaglepass.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sporecast-frontend
                port:
                  number: 80
