apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName.name }}"
  labels:
    app: "{{ .Values.appName.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName.name }}"
    spec:
      containers:
        - name: "{{ .Values.appName.name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.policy }}"
          ports:
            - containerPort: "{{ .Values.image.containerPort }}"
          env:
          {{- include "custom.envMap" .Values.env | indent 6 }}
          volumeMounts:
            {{- if .Values.nfs.enabled }}
            - name: remote-config
              mountPath: /app/backend/data
            {{- end }}
      volumes:
        {{- if .Values.nfs.enabled }}
        - name: remote-config
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
        {{- end }}