apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.ingress.targetPort }}
  selector:
    app: {{ .Values.appName }}