apiVersion: v2
name: wolf
description: Wolf streaming server for Moonlight - stream games from Docker containers
type: application
version: 0.1.0
appVersion: "stable"
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
