apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      containers:
        - name: "{{ .Values.app.name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.policy }}"
          ports:
            - name: http
              containerPort: 8056
              protocol: TCP
          env:
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: JFA_DATA
              value: "{{ .Values.env.JFA_DATA }}"
            - name: JFA_BASE_URL
              value: "{{ .Values.env.JFA_BASE_URL }}"
            - name: JFA_FROM_ADDRESS
              value: "{{ .Values.env.JFA_FROM_ADDRESS }}"
            - name: JELLYFIN_URL
              value: "{{ .Values.env.JELLYFIN_URL }}"
            - name: JELLYFIN_PUBLIC_URL
              value: "{{ .Values.env.JELLYFIN_PUBLIC_URL }}"
            - name: SONARR_URL
              value: "{{ .Values.env.SONARR_URL }}"
            - name: RADARR_URL
              value: "{{ .Values.env.RADARR_URL }}"
            - name: RADARR_QUALITY_PROFILE
              value: "{{ .Values.env.RADARR_QUALITY_PROFILE }}"
            - name: RADARR_LANGUAGE_PROFILE
              value: "{{ .Values.env.RADARR_LANGUAGE_PROFILE }}"
            - name: SONARR_QUALITY_PROFILE
              value: "{{ .Values.env.SONARR_QUALITY_PROFILE }}"
            - name: SONARR_LANGUAGE_PROFILE
              value: "{{ .Values.env.SONARR_LANGUAGE_PROFILE }}"
            - name: PARTIAL_SEASONS
              value: "{{ .Values.env.PARTIAL_SEASONS }}"
            - name: RADARR__API
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.opSecret.RADARR__API.secretName }}"
                  key: "{{ .Values.opSecret.RADARR__API.key }}"
            - name: SONARR__API
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.opSecret.SONARR__API.secretName }}"
                  key: "{{ .Values.opSecret.SONARR__API.key }}"
            - name: JELLYFIN__API
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.opSecret.JELLYFIN__API.secretName }}"
                  key: "{{ .Values.opSecret.JELLYFIN__API.key }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          nfs:
            server: {{ .Values.volumes.nfs.server }}
            path: {{ .Values.volumes.nfs.path }}
