apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app.name }}"
  labels:
    app: "{{ .Values.app.name }}"
  annotations:
    external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jfa.eaglepass.io
      secretName: jfa-tls-certificate
  rules:
    - host: jfa.eaglepass.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.app.name }}"
                port:
                  number: 8056
