app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/embystat
            tag: latest
          env:
            PUID: "99"
            PGID: "100"
            TZ: America/Chicago
  service:
    main:
      ports:
        http:
          port: 6555
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &embystatHost embystat.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *embystatHost
          secretName: embystat-tls-certificate
  persistence:
    nfs-restore:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/embystat_config
      advancedMounts:
        main:
          main:
            - path: /config