apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.MYSQL_ROOT_PASSWORD.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.MYSQL_ROOT_PASSWORD.vault }}/items/{{ .Values.opSecret.MYSQL_ROOT_PASSWORD.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.MYSQL_DATABASE.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.MYSQL_DATABASE.vault }}/items/{{ .Values.opSecret.MYSQL_DATABASE.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.MYSQL_USER.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.MYSQL_USER.vault }}/items/{{ .Values.opSecret.MYSQL_USER.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.MYSQL_PASSWORD.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.MYSQL_PASSWORD.vault }}/items/{{ .Values.opSecret.MYSQL_PASSWORD.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.ENCRYPTION_KEY.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.ENCRYPTION_KEY.vault }}/items/{{ .Values.opSecret.ENCRYPTION_KEY.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.JWT_SECRET.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.JWT_SECRET.vault }}/items/{{ .Values.opSecret.JWT_SECRET.item }}"