#https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml for all options
app-template:
  controllers:
    main:
      containers:
        main:
          name: main
          image:
            repository: lscr.io/linuxserver/emby
            tag: latest
          env:
            PUID: "99"
            PGID: "100"
            TZ: "America/Chicago"
            NVIDIA_VISIBLE_DEVICES: "all"
            NVIDIA_DRIVER_CAPABILITIES: "all"
            FFMPEG_HWACCEL: "cuda"
          resources:
            limits:
              cpu: 4
              memory: "8192Mi"
            requests:
              cpu: 2
              memory: "4096Mi"
      initContainers:
        restore:
          name: restore
          image:
            repository: alpine
            tag: latest
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "[INFO] Checking for /config/bees-knees marker file..."
              if [ -f /config/bees-knees ]; then
                echo "[INFO] Restore skipped: /config/bees-knees exists."
                exit 0
              fi

              BACKUP_DIR="/backups/embyserver-backup-full"
              DEST_DIR="/config"
              FOLDERS="config metadata root data plugins"

              # Check all folders exist in backup
              for folder in $FOLDERS; do
                if [ ! -d "$BACKUP_DIR/$folder" ]; then
                  echo "[ERROR] Backup folder $BACKUP_DIR/$folder not found. Aborting restore."
                  exit 1
                fi
              done

              # Restore folders (overwrite if exists)
              for folder in $FOLDERS; do
                echo "[INFO] Restoring $folder to $DEST_DIR..."
                rm -rf "$DEST_DIR/$folder"
                cp -a "$BACKUP_DIR/$folder" "$DEST_DIR/"
                echo "[INFO] Restored $folder."
              done

              touch /config/bees-knees
              echo "[INFO] Restore complete. Marker file created at /config/bees-knees."
  service:
    main:
      primary: true
      ports:
        http:
          port: 8096
          protocol: HTTP
        http2:
          port: 8920
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &embyHost emby.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &emby-healthHost emby-health.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http2
      tls:
        - hosts:
            - *embyHost
            - *emby-healthHost
          secretName: emby-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 20Gi
      advancedMounts:
        main:
          main:
            - path: /config
          restore:
            - path: /config
    transcode:
      type: hostPath
      hostPath: /emby/transcode
      advancedMounts:
        main:
          main:
            - path: /emby/transcode
    nfs-restore:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/emby_backups
      advancedMounts:
        main:
          main:
            - path: /backups
          restore:
            - path: /backups
    nfs-movies:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/movies
      advancedMounts:
        main:
          main:
            - path: /data/movies
    nfs-tv:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/tv
      advancedMounts:
        main:
          main:
            - path: /data/tv
    nfs-music:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/music
      advancedMounts:
        main:
          main:
            - path: /data/music
  defaultPodOptions:
    tolerations:
      - key: "dedicated"
        value: "sprigatito"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "sprigatito"
    runtimeClassName: nvidia