#https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml for all options
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/comfyanonymous/comfyui
            tag: latest
          env:
            PUID: "99"
            PGID: "100"
            TZ: America/Chicago
            NVIDIA_VISIBLE_DEVICES: "all"
            NVIDIA_DRIVER_CAPABILITIES: "all"
            PORT: "8188"
  service:
    main:
      ports:
        http:
          port: 8188
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &embyHost comfyui.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *embyHost
          secretName: comfyui-tls-certificate
  # persistence:
  #   data:
  #     accessMode: ReadWriteOnce
  #     size: 100Gi
  #     advancedMounts:
  #       main:
  #         main:
  #           - path: /config
  #         restore:
  #           - path: /config
  defaultPodOptions:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu.present
                  operator: In
                  values:
                    - "true"
    runtimeClassName: nvidia