app-template:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: RollingUpdate
      containers:
        main:
          name: main
          image:
            repository: ghcr.io/ai-dock/comfyui
            tag: v2-cuda-12.1.1-base-22.04-v0.2.7
            pullPolicy: IfNotPresent
          env:
            TZ: "America/Chicago"
            SERVICEPORTAL_URL: ""
            CF_QUICK_TUNNELS: "false"
            WEB_ENABLE_HTTPS: "false"
            COMFYUI_URL: "https://comfyui.eaglepass.io"
            SYNCTHING_UI_PORT_HOST: "0"
            SYNCTHING_TRANSPORT_PORT_HOST: "0"
            SYNCTHING_URL: ""
            NVIDIA_VISIBLE_DEVICES: "all"
            NVIDIA_DRIVER_CAPABILITIES: "all"
            FFMPEG_HWACCEL: "cuda"
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1200m
              memory: 6144Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8188
                initialDelaySeconds: 30
                periodSeconds: 10
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8188
                initialDelaySeconds: 10
                periodSeconds: 10
  service:
    main:
      ports:
        http:
          port: 8188
          protocol: HTTP
        portal:
          port: 1111
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host comfyui.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: comfyui-tls-certificate
  persistence:
    models:
      accessMode: ReadWriteOnce
      size: 60Gi
      globalMounts:
        - path: /comfyui/models
    input:
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /comfyui/input
    output:
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /comfyui/output
  defaultPodOptions:
    tolerations:
      - key: "dedicated"
        value: "arcanine"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "arcanine"
    runtimeClassName: nvidia
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
