app-template:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: RollingUpdate
      containers:
        main:
          name: main
          image:
            repository: brimdor/comfyui
            tag: cuda
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            NVIDIA_VISIBLE_DEVICES: "all"
            NVIDIA_DRIVER_CAPABILITIES: "all"
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1200m
              memory: 6144Mi
              nvidia.com/gpu: 1
          probes:
            liveness:
              enabled: false
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8188
                initialDelaySeconds: 30
                periodSeconds: 10
            readiness:
              enabled: false
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8188
                initialDelaySeconds: 10
                periodSeconds: 10
            startup:
              enabled: false
              custom: true
  service:
    main:
      ports:
        http:
          port: 8188
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host comfyui.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: comfyui-tls-certificate
  persistence:
    models:
      accessMode: ReadWriteOnce
      size: 60Gi
      globalMounts:
        - path: /app/models
    input:
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /app/input
    output:
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /app/output
  defaultPodOptions:
    tolerations:
      - key: "dedicated"
        value: "arcanine"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "arcanine"
    runtimeClassName: nvidia
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
