apiVersion: v2
name: unsloth
description: A Helm chart for deploying Unsloth with bjw-s app-template
home: https://unsloth.ai/docs
sources:
  - https://github.com/unslothai/unsloth
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
