apiVersion: v2
name: heartlib
description: A Helm chart for deploying HeartLib music foundation model using bjw-s app-template
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.6.0
    repository: https://bjw-s-labs.github.io/helm-charts
