# https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: josh5/steam-headless
            tag: latest
            pullPolicy: Always
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_NICE
            seccompProfile:
              type: Unconfined
          resources:
            limits:
              cpu: 2000m
              memory: 12Gi
            requests:
              cpu: 2000m
              memory: 12Gi
          networkMode: host
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            TZ: "America/Chicago"
            USER_LOCALES: "en_US.UTF-8"
            DISPLAY: ":0"
            PUID: "1000"
            PGID: "1000"
            UMASK: "000"
            USER_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "user-password"
            MODE: "primary"
            HOST_DBUS: "true"
            WEB_UI_MODE: "vnc"
            ENABLE_VNC_AUDIO: "false"
            PORT_NOVNC_WEB: "8083"
            NEKO_NAT1TO1: ""
            ENABLE_STEAM: "true"
            STEAM_ARGS: "-silent"
            STEAM_ARGS: ""
            ENABLE_SUNSHINE: "true"
            SUNSHINE_USER:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sunshine-user"
            SUNSHINE_PASS:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sunshine-pass"
            ENABLE_EVDEV_INPUTS: "true"
            FORCE_X11_DUMMY_CONFIG: "false"
            NVIDIA_DRIVER_CAPABILITIES: "all"
            NVIDIA_VISIBLE_DEVICES: "all"
          resources: {}
          shmSize: 4Gi
          volumeMounts:
            - name: data
              mountPath: /home/default
            - name: games-dir
              mountPath: /mnt/games
            - name: x11-unix
              mountPath: /tmp/.X11-unix
            - name: pulse
              mountPath: /tmp/pulse
            - name: dev-fuse
              mountPath: /dev/fuse
            - name: dev-input
              mountPath: /dev/input
            - name: dbus-socket
              mountPath: /run/dbus
          ulimits:
            nofile:
              soft: 1024
              hard: 524288
      hostNetwork: true
      hostIPC: true
      hostname: "SteamHeadless"
      extraHosts:
        - "SteamHeadless:127.0.0.1"
      deviceCgroupRules:
        - "c 13:* rmw"

  service:
    main:
      ports:
        http:
          port: 8083
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &Host steam.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *Host
          secretName: steam-tls-certificate

  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 30Gi
      advancedMounts:
        main:
          main:
            - path: /home/default
    games-dir:
      accessMode: ReadWriteOnce
      size: 150Gi
      advancedMounts:
        main:
          main:
            - path: /mnt/games
    x11-unix:
      type: hostPath
      hostPath: /opt/container-data/steam-headless/sockets/.X11-unix
      advancedMounts:
        main:
          main:
            - path: /tmp/.X11-unix
    pulse:
      type: hostPath
      hostPath: /opt/container-data/steam-headless/sockets/pulse
      advancedMounts:
        main:
          main:
            - path: /tmp/pulse
    dev-fuse:
      type: hostPath
      hostPath: /dev/fuse
      advancedMounts:
        main:
          main:
            - path: /dev/fuse
    dev-uinput:
      type: hostPath
      hostPath: /dev/input
      advancedMounts:
        main:
          main:
            - path: /dev/input
    dbus-socket:
      type: hostPath
      hostPath: /run/dbus
      advancedMounts:
        main:
          main:
            - path: /run/dbus

  defaultPodOptions:
    hostname: steam-headless
    hostIPC: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu.present
                  operator: In
                  values:
                    - "true"
    runtimeClassName: nvidia
    annotations:
      operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/blko56xpckrxxxm6cnfxyz2kpq"
      operator.1password.io/item-name: "secrets"