apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  volumeName: openwebui-nfs-pv
  storageClassName: openwebui-nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-embedded-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo