- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - prerequisites
    - k3s
    - nfs_utils
    - cronjobs
    - automatic_upgrade

- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - cilium
