- name: Setup Nodes
  hosts: metal
  roles:
    - system_settings
    - nfs_utils
    - podman
    - docker
    - cronjobs
    - { role: virtualization, when: inventory_hostname == "arcanine" }
    - { role: display_config, when: inventory_hostname == "arcanine" }