- name: Setup Nodes
  hosts: metal
  roles:
    - system_settings
    - nfs_utils
    - podman
    - docker
    - cronjobs
    - role: virtualization
      when: "{{ hostvars[inventory_hostname].has_virtualization | default(false) }}"
      tags: virtualization
    - role: display_config
      when: "{{ hostvars[inventory_hostname].has_display | default(false) }}"
      tags: display_config
