apiVersion: v2
name: n8n-canary
description: Umbrella chart to deploy n8n (8gears official chart) with an in-cluster PostgreSQL and NFS-based backups
version: 0.1.0
type: application

# Use the official n8n chart by 8gears (OCI)
dependencies:
  - name: n8n
    version: 1.0.11
    repository: oci://8gears.container-registry.com/library
