all:
  vars:
    control_plane_endpoint: 10.0.20.50
    load_balancer_ip_pool:
      - 10.0.20.224/27
metal:
  children:
    masters:
      hosts:
        charmander:
          {
            ansible_host: 10.0.20.11,
            mac: "00:23:24:b0:ff:03",
            disk: sda,
            network_interface: eno1,
          }
        squirtle:
          {
            ansible_host: 10.0.20.12,
            mac: "00:23:24:e2:1f:a1",
            disk: sda,
            network_interface: eno1,
          }
        bulbasaur:
          {
            ansible_host: 10.0.20.13,
            mac: "00:23:24:e2:0d:ea",
            disk: sda,
            network_interface: eno1,
          }
    workers:
      hosts:
        pikachu:
          {
            ansible_host: 10.0.20.14,
            mac: "e0:4f:43:24:0b:53",
            disk: sda,
            network_interface: eno1,
          }
        chikorita:
          {
            ansible_host: 10.0.20.15,
            mac: "6c:4b:90:60:29:c4",
            disk: sda,
            network_interface: eno1,
          }
        cyndaquil:
          {
            ansible_host: 10.0.20.16,
            mac: "6c:4b:90:5f:8e:43",
            disk: sda,
            network_interface: eno1,
          }
        totodile:
          {
            ansible_host: 10.0.20.17,
            mac: "6c:4b:90:5b:a3:56",
            disk: sda,
            network_interface: eno1,
          }
        growlithe:
          {
            ansible_host: 10.0.20.18,
            mac: "6c:4b:90:5b:6e:6d",
            disk: sda,
            network_interface: eno1
          }
        arcanine:
          {
            ansible_host: 10.0.20.19,
            mac: "4c:cc:6a:3d:e5:3f",
            disk: sda,
            network_interface: eno1,
            gpu_type: 'GeForce RTX 3090',
            has_display: true,
            has_virtualization: true
          }
        sprigatito:
          {
            ansible_host: 10.0.20.20,
            mac: "4c:cc:6a:34:dc:6d",
            disk: sda,
            network_interface: eno1,
            gpu_type: 'GeForce GTX 1650',
            has_virtualization: true
          }
