app-template:
  controllers:
    cloudflared:
      containers:
        app:
          image:
            repository: docker.io/cloudflare/cloudflared
            tag: 2026.5.2
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
  configMaps:
    config:
      enabled: true
      data:
        config.yaml: |
          tunnel: homelab
          credentials-file: /etc/cloudflared/credentials.json
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          ingress:
            - hostname: 'citadel.eaglepass.io'
              service: https://command-central.tail18136a.ts.net:443
              originRequest:
                noTLSVerify: true
            - hostname: 'hermes-webhook.eaglepass.io'
              service: http://10.0.30.100:8644
              originRequest:
                noTLSVerify: true
            - hostname: '*.eaglepass.io'
              service: https://ingress-nginx-controller.ingress-nginx
              originRequest:
                noTLSVerify: true
            - service: http_status:404
  persistence:
    config:
      enabled: true
      type: configMap
      name: cloudflared
      globalMounts:
        - path: /etc/cloudflared/config.yaml
          subPath: config.yaml
    credentials:
      enabled: true
      type: secret
      name: cloudflared-credentials
      globalMounts:
        - path: /etc/cloudflared/credentials.json
          subPath: credentials.json
