apiVersion: apps/v1
kind: Deployment
metadata:
  name: backlog-companion
  labels:
    app: backlog-companion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backlog-companion
  template:
    metadata:
      labels:
        app: backlog-companion
    spec:
      containers:
        - name: backlog-companion
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backlog-companion-secrets
                  key: STEAM_API_KEY
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}
