# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backlog-companion
  labels:
    app: backlog-companion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backlog-companion
  template:
    metadata:
      labels:
        app: backlog-companion
    spec:
      containers:
        - name: backlog-companion
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backlog-companion-secrets
                  key: STEAM_API_KEY
            - name: FLASK_APP
              value: "backend/app.py"
          volumeMounts:
            # - name: backlog-companion-data
            #   mountPath: /app/backend/data
            {{- if .Values.nfs.enabled }}
            - name: remote-config
              mountPath: /app/backend/data
            {{- end }}
      volumes:
        # - name: backlog-companion-data
        #   persistentVolumeClaim:
        #     claimName: {{ .Values.persistence.name }}
        {{- if .Values.nfs.enabled }}
        - name: remote-config
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
        {{- end }}
