apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.externalSecret.name }}
    template:
      type: Opaque
  data:
    - secretKey: STEAM_API_KEY
      remoteRef:
        key: steam-api-key-secret
        property: STEAM_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.externalSecret.name }}