apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backlog-companion-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.externalDnsTarget | quote }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
{{- range .Values.ingress.tls }}
    - hosts:
{{- range .hosts }}
        - {{ . | quote }}
{{- end }}
      secretName: {{ .secretName | quote }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: backlog-companion
                port:
                  name: http
{{- end }}
{{- end }}