apiVersion: onepassword.com/v1
kind: OnePasswordItem

  name: "{{ .Values.opSecret.secretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  itemPath: "vaults/{{ .Values.opSecret.vault }}/items/{{ .Values.opSecret.item }}"