apiVersion: v1
kind: Service
metadata:
  name: backlog-companion
spec:
  type: ClusterIP
  selector:
    app: backlog-companion
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: backend
      port: 3000
      targetPort: 3000
    - name: frontend
      port: 80
      targetPort: 80
