apiVersion: v1
kind: Service
metadata:
  name: backlog-companion
  # labels:
  #   app: backlog-companion
  #   app.kubernetes.io/name: backlog-companion
  #   app.kubernetes.io/instance: backlog-companion
spec:
  type: ClusterIP
  selector:
    app: backlog-companion
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: http
      port: 80
      targetPort: 80
    - name: backend
      port: 3000
      targetPort: 3000
    # - name: frontend
    #   port: 80
    #   targetPort: 80
