apiVersion: v2
name: ace-step
description: Helm chart for deploying Ace-Step via the bjw-s app-template library chart
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
