createNamespace: false
createPVs: true
createPVCs: true

nfs:
  server: 10.0.40.3
  basePath: /mnt/user/nextcloud
  storageClass: nfs

nextcloud:
  image:
    registry: docker.io
    repository: library/nextcloud
    flavor: apache

  replicaCount: 1

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    path: /
    pathType: Prefix
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - nextcloud.eaglepass.io

  phpClientHttpsFix:
    enabled: true
    protocol: https

  nextcloud:
    host: nextcloud.eaglepass.io
    trustedDomains:
      - nextcloud.eaglepass.io
      - nextcloud.kube.home
    username: admin
    password: changeme

  internalDatabase:
    enabled: false

  externalDatabase:
    enabled: true
    type: mysql
    existingSecret:
      enabled: false
      usernameKey: db-username
      passwordKey: db-password

  mariadb:
    enabled: true
    architecture: standalone
    auth:
      database: nextcloud
      username: nextcloud
      password: changeme
      rootPassword: changeme
    primary:
      persistence:
        enabled: true
        existingClaim: nextcloud-mysql-root
        subPath: mysql

  persistence:
    enabled: true
    existingClaim: nextcloud-config
    nextcloudData:
      enabled: true
      existingClaim: nextcloud-data
