# values.yaml for bolt-diy Helm chart using bjw-s common chart
# See https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml for all options
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: linuxserver/sabnzbd
            tag: latest
            pullPolicy: Always
          env:
            PUID: "99"
            PGID: "100"
            TZ: "America/Chicago"
        fixHost:
          image:
            repository: alpine
            tag: latest
          name: fixHost
          command:
            - /bin/sh
            - -c
            - |
              # Wait for sabnzbd.ini to exist
              while [ ! -f /config/sabnzbd.ini ]; do
                echo "Waiting for /config/sabnzbd.ini to be created..."
                sleep 5
              done

              if [ ! -f /config/bees-knees ]; then
                if grep -q '^host_whitelist =' /config/sabnzbd.ini; then
                  sed -i '/^host_whitelist =.*/c\host_whitelist = sabnzbd.eaglepass.io' /config/sabnzbd.ini
                else
                  echo 'host_whitelist = sabnzbd.eaglepass.io' >> /config/sabnzbd.ini
                fi
                touch /config/bees-knees
              fi

              sleep infinity
  service:
    main:
      controller: main
      primary: true
      type: ClusterIP
      externalTrafficPolicy:
      ports:
        http:
          port: 8080
          protocol: HTTP
    connect:
      controller: main
      ClusterIP: 10.43.10.13
      ports:
        http:
          port: 8080
          targetPort: 8080
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: sabnzbd.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - sabnzbd.eaglepass.io
          secretName: sabnzbd-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        main:
          main:
            - path: /config
          backup:
            - path: /config
    nfs-intermediate:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/sabnzbd_inter
      advancedMounts:
        main:
          main:
            - path: /incomplete-downloads
    nfs-backups:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/sabnzbd_backups
      advancedMounts:
        main:
          main:
            - path: /backups
    nfs-downloads:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/downloads
      advancedMounts:
        main:
          main:
            - path: /downloads
    nfs-apps:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/apps
      advancedMounts:
        main:
          main:
            - path: /apps
