apiVersion: v1
kind: ConfigMap
metadata:
  name: pages-canary-demo
  namespace: pages-canary
data:
{{- $files := .Files }}
{{- range $path, $_ := $files.Glob "demo/**.html" }}
  {{ base $path }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}