# This values.yaml only overrides homelab-relevant settings. All other defaults
# are inherited from the upstream chart (pinned in Chart.yaml dependencies).
# Upstream chart: https://github.com/weaviate/weaviate-helm (repo URL: https://weaviate.github.io/weaviate-helm)

# Image settings. Default repository/tag align with upstream.
image:
  repository: cr.weaviate.io/semitechnologies/weaviate
  # Default to upstream appVersion. You can opt-in to "latest" explicitly.
  tag: "1.32.3"
  pullPolicy: IfNotPresent

# Number of replicas for the Weaviate deployment/statefulset (upstream handles controller type).
replicaCount: 1

# Ingress configuration. Disabled by default. Enable and set hosts to expose externally.
ingress:
  enabled: false
  className: "" # e.g., nginx
  annotations: {}
  hosts: []
  # - host: weaviate.example.com
  #   paths:
  #     - path: /
  #       pathType: Prefix
  tls: []
  # - secretName: weaviate-tls
  #   hosts:
  #     - weaviate.example.com

# Persistence for Weaviate data. Upstream supports persistence; expose key knobs here.
persistence:
  enabled: true # set false to run ephemeral
  existingClaim: "" # if provided, overrides storageClass/size
  storageClass: "" # e.g., rook-ceph-block
  accessModes: ["ReadWriteOnce"]
  size: 10Gi
  # Homelab convention: the first PVC should be semantically "data". Upstream naming
  # may vary; consult upstream values for exact claim names.

# Resource requests/limits left empty by default. Set as needed.
resources: {}
  # requests:
  #   cpu: "500m"
  #   memory: "2Gi"
  # limits:
  #   cpu: "2"
  #   memory: "8Gi"

# Env variables passed to Weaviate container. Use for non-sensitive overrides.
env: {}
  # EXAMPLE:
  # - name: QUERY_DEFAULTS_LIMIT
  #   value: "100"

# Non-sensitive configuration rendered via a ConfigMap. Keys map to config file
# fragments the upstream chart can mount. See README for examples and docs.
config: {}
  # example-config.yaml: |
  #   some: config
  #   go: here

# Secrets are NOT stored here. Use 1Password Operator to inject secrets into a
# Kubernetes Secret named "secrets" and consume via env.valueFrom.secretKeyRef.
# DO NOT commit secret values.
secrets: {}
  # Provide references like this in env (above):
  # - name: SOME_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: secrets
  #       key: some-password
  # 1Password Operator annotations (example) must be added at Pod/Workload level
  # via upstream values or by setting pod annotations in this chart's values if exposed:
podAnnotations: {}
  # operator.1password.io/item-path: "vaults/<vault-id>/items/<item-id>"
  # operator.1password.io/item-name: "secrets"

# Metrics block (if supported by upstream; left as passthrough)
metrics: {}

# Backup configuration — disabled by default. When enabled, a CronJob will
# tar/rsync the Weaviate data directory to an NFS share.
backup:
  enabled: false
  nfsServer: 10.0.50.3
  nfsPath: "/path/to/backup" # CHANGE THIS before enabling backups
  schedule: "*/15 * * * *"
  retentionDays: 7
  # Implementation note: this sub-chart does not ship templates; use an umbrella
  # or platform-level backup CronJob wired to the Weaviate PVC. See README.
