# values.yaml for Weaviate using the upstream Weaviate Helm sub-chart

# Upstream sub-chart values are nested under the dependency name 'weaviate'
weaviate:
  image:
    registry: cr.weaviate.io
    repo: semitechnologies/weaviate
    tag: "latest"
    pullPolicy: IfNotPresent
    pullSecrets: []

  # Non-sensitive environment variables
  env:
    QUERY_MAXIMUM_RESULTS: 100000
    PROMETHEUS_MONITORING_ENABLED: "false"

  # Map env vars to a Kubernetes Secret name (the key must match the env var name)
  envSecrets:
    ROOT_PASSWORD: secrets

  # Internal service configuration
  service:
    name: weaviate
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
    annotations: {}

  # Upstream chart storage configuration
  storage:
    size: 32Gi
    storageClassName: ""
  # Note: upstream chart manages its own StatefulSet volumeClaimTemplates (name: weaviate-data).
  # We rely on that PVC and target it in backups via backups.pvcName.

  # gRPC service for internal access
  grpcService:
    enabled: true
    type: ClusterIP
    ports:
      - name: grpc
        protocol: TCP
        port: 50051
    annotations: {}

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# 1Password Operator secret annotations configuration
secret:
  # Set after running tools/weaviate-op-create.sh
  itemPath: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/xe4jnzi46s7xonfwgsvkyuvapa"

# Backups CronJob settings (backs up the 'data' PVC to NFS)
backups:
  enabled: true
  schedule: "*/15 * * * *"
  retentionDays: 7
  pvcName: "weaviate-data-weaviate-0"
  nfs:
    server: "10.0.50.3"
    path: "/path/to/backups/weaviate" # placeholder, customize in your environment
  labels: {}
  annotations: {}
  podResources: {}

# Wrapper chart-managed Ingress (preferred)
ingress:
  enabled: false
  className: nginx
  annotations:
    # external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: weaviate.eaglepass.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: weaviate-tls-certificate
      hosts:
        - weaviate.eaglepass.io
  # Service backend settings for this Ingress
  serviceName: weaviate
  servicePort: http
