# Use defaults and override only what's needed
use_default_settings: true
server:
  bind_address: 0.0.0.0
  port: 8080
  base_url: "https://searxng.eaglepass.io"
ui:
  # Minimal UI options; adjust theme if desired
  default_theme: simple
  static_use_hash: true

search:
  # Ensure JSON is allowed for API clients like Open WebUI
  formats:
    - html
    - json
  # Language and safe search defaults
  safe_search: 0
  language: "en-US"

default_categories:
  - general
  - images
  - videos
  - news
  - map
  - music
  - it
  - science
  - files
  - social media

engines:
  # ----- General (top 5) -----
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: [general]
    disabled: false

  - name: google
    engine: google
    shortcut: go
    categories: [general]
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    categories: [general, web]
    brave_category: search
    disabled: false

  - name: startpage
    engine: startpage
    shortcut: sp
    startpage_categ: web
    categories: [general, web]
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox"]
    categories: [general]
    disabled: false

  # ----- Images (top 5) -----
  - name: google images
    engine: google_images
    shortcut: goi
    categories: [images]
    disabled: false

  - name: bing images
    engine: bing_images
    shortcut: bii
    categories: [images]
    disabled: false

  - name: flickr
    engine: flickr_noapi
    shortcut: fl
    categories: [images]
    disabled: false

  - name: openverse
    engine: openverse
    shortcut: opv
    categories: [images]
    disabled: false

  - name: wikicommons.images
    engine: wikicommons
    shortcut: wc
    search_type: images
    number_of_results: 10
    categories: [images]
    disabled: false

  # ----- Videos (top 5) -----
  - name: google videos
    engine: google_videos
    shortcut: gov
    categories: [videos]
    disabled: false

  - name: bing videos
    engine: bing_videos
    shortcut: biv
    categories: [videos]
    disabled: false

  - name: youtube
    engine: youtube_noapi
    shortcut: yt
    categories: [videos]
    disabled: false

  - name: vimeo
    engine: vimeo
    shortcut: vm
    categories: [videos]
    disabled: false

  - name: dailymotion
    engine: dailymotion
    shortcut: dm
    categories: [videos]
    disabled: false

  # ----- News (top 5) -----
  - name: google news
    engine: google_news
    shortcut: gon
    categories: [news]
    disabled: false

  - name: bing news
    engine: bing_news
    shortcut: bin
    categories: [news]
    disabled: false

  - name: startpage news
    engine: startpage
    startpage_categ: news
    shortcut: spn
    categories: [news, web]
    disabled: false

  - name: reuters
    engine: reuters
    shortcut: reu
    categories: [news]
    disabled: false

  - name: yahoo news
    engine: yahoo_news
    shortcut: yhn
    categories: [news]
    disabled: false

  # ----- Map (available 3) -----
  - name: openstreetmap
    engine: openstreetmap
    shortcut: osm
    categories: [map]
    disabled: false

  - name: photon
    engine: photon
    shortcut: ph
    categories: [map]
    disabled: false

  - name: apple maps
    engine: apple_maps
    shortcut: apm
    timeout: 5.0
    categories: [map]
    disabled: false

  # ----- Music (top 5) -----
  - name: soundcloud
    engine: soundcloud
    shortcut: sc
    categories: [music]
    disabled: false

  - name: bandcamp
    engine: bandcamp
    shortcut: bc
    categories: [music]
    disabled: false

  - name: mixcloud
    engine: mixcloud
    shortcut: mc
    categories: [music]
    disabled: false

  - name: piped.music
    engine: piped
    network: piped
    shortcut: ppdm
    piped_filter: music_songs
    timeout: 3.0
    categories: [music]
    disabled: false

  - name: podcastindex
    engine: podcastindex
    shortcut: podcast
    categories: [music]
    disabled: false

  # ----- IT (top 5) -----
  - name: stackoverflow
    engine: stackexchange
    api_site: 'stackoverflow'
    shortcut: st
    categories: [it, q&a]
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    categories: [it, repos]
    disabled: false

  - name: pypi
    engine: pypi
    shortcut: pypi
    categories: [it, packages]
    disabled: false

  - name: docker hub
    engine: docker_hub
    shortcut: dh
    categories: [it, packages]
    disabled: false

  - name: mdn
    engine: json_engine
    shortcut: mdn
    paging: true
    search_url: https://developer.mozilla.org/api/v1/search?q={query}&page={pageno}
    results_query: documents
    url_query: mdn_url
    url_prefix: https://developer.mozilla.org
    title_query: title
    content_query: summary
    categories: [it]
    disabled: false

  # ----- Science (top 5) -----
  - name: google scholar
    engine: google_scholar
    shortcut: gos
    categories: [science]
    disabled: false

  - name: arxiv
    engine: arxiv
    shortcut: arx
    timeout: 4.0
    categories: [science]
    disabled: false

  - name: pubmed
    engine: pubmed
    shortcut: pub
    timeout: 3.0
    categories: [science]
    disabled: false

  - name: wikispecies
    engine: mediawiki
    shortcut: wsp
    base_url: "https://species.wikimedia.org/"
    search_type: text
    categories: [science, wikimedia]
    disabled: false

  - name: pdbe
    engine: pdbe
    shortcut: pdb
    categories: [science]
    disabled: false

  # ----- Files (top 5) -----
  - name: solidtorrents
    engine: solidtorrents
    shortcut: solid
    timeout: 4.0
    base_url:
      - https://solidtorrents.to
      - https://bitsearch.to
    categories: [files]
    disabled: false

  - name: piratebay
    engine: piratebay
    shortcut: tpb
    url: https://thepiratebay.org/
    timeout: 3.0
    categories: [files]
    disabled: false

  - name: bt4g
    engine: bt4g
    shortcut: bt4g
    categories: [files]
    disabled: false

  - name: wikicommons.files
    engine: wikicommons
    shortcut: wcf
    search_type: files
    number_of_results: 10
    categories: [files]
    disabled: false

  - name: 1337x
    engine: 1337x
    shortcut: 1337x
    categories: [files]
    disabled: false

  # ----- Social media (top 5) -----
  - name: mastodon users
    engine: mastodon
    mastodon_type: accounts
    base_url: https://mastodon.social
    shortcut: mau
    categories: ["social media"]
    disabled: false

  - name: mastodon hashtags
    engine: mastodon
    mastodon_type: hashtags
    base_url: https://mastodon.social
    shortcut: mah
    categories: ["social media"]
    disabled: false

  - name: lemmy communities
    engine: lemmy
    lemmy_type: Communities
    shortcut: leco
    categories: ["social media"]
    disabled: false

  - name: lemmy posts
    engine: lemmy
    lemmy_type: Posts
    network: lemmy communities
    shortcut: lepo
    categories: ["social media"]
    disabled: false

  - name: tootfinder
    engine: tootfinder
    shortcut: toot
    categories: ["social media"]
    disabled: false


# Basic bot-detection knobs; tailor pass/block lists for cluster ranges
botdetection:
  ip_lists:
    block_ip: []
    pass_ip: []
  link_token: false

# Outgoing network timeouts
outgoing:
  request_timeout: 6.0
  max_redirects: 3
  pool_connections: 10
  pool_maxsize: 20

# CORS for API use if accessing directly (ingress usually handles this)
http:
  method: GET
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS"
    Access-Control-Allow-Headers: "Content-Type, X-Requested-With"

# Logging verbosity
logging:
  version: 1
  disable_existing_loggers: false
  root:
    level: INFO
    handlers: [console]
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
