apiVersion: v2
name: media-cleaner
description: A Helm chart for media-cleaner bot
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 3.2.1
