app-template:
  controllers:
    main:
      type: statefulset
      initContainers:
        reindex:
          image:
            repository: docker.io/kanidm/server
            tag: "1.4.0"
            pullPolicy: IfNotPresent
          command: ["/sbin/kanidmd","database","reindex","-c","/data/server.toml"]
      containers:
        main:
          image:
            repository: docker.io/kanidm/server
            tag: "1.4.0"

  # your existing config stays the same ↓
  statefulset:
    volumeClaimTemplates:
      - name: data
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /data

  configMaps:
    config:
      enabled: true
      data:
        server.toml: |
          bindaddress = "[::]:443"
          ldapbindaddress = "[::]:636"
          db_path = "/data/kanidm.db"
          tls_chain = "/data/ca.crt"
          tls_key = "/data/tls.key"
          domain = "auth.eaglepass.io"
          origin = "https://auth.eaglepass.io"

  persistence:
    config:
      enabled: true
      type: configMap
      name: kanidm-config
      globalMounts:
        - path: /data/server.toml
          subPath: server.toml
    tls:
      enabled: true
      type: secret
      name: kanidm-selfsigned-certificate
      globalMounts:
        - path: /data/ca.crt
          subPath: ca.crt
        - path: /data/tls.key
          subPath: tls.key

  service:
    main:
      ports:
        http:
          enabled: false
        https:
          port: 443
          protocol: HTTPS
        ldap:
          port: 636
          protocol: TCP

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      hosts:
        - host: &host auth.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: https
      tls:
        - hosts: [*host]
          secretName: kanidm-tls-certificate
