# values.yaml for bolt-diy Helm chart using bjw-s common chart
# See https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml for all options
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/bolt.diy
            tag: latest
            pullPolicy: Always
          env:
            NODE_ENV: production
            COMPOSE_PROFILES: production
            PORT: 5173
            OPENAI_API_KEY:
              valueFrom:
                  secretKeyRef:
                    name: "openai-api-key"
                    key: "openai-api-key"
            RUNNING_IN_DOCKER: "true"
            VITE_LOG_LEVEL: "debug"
            DEFAULT_NUM_CTX: "32768"
            VITE_GITHUB_ACCESS_TOKEN:
              valueFrom:
                  secretKeyRef:
                    name: "github-access-token"
                    key: "github-access-token"
            VITE_GITHUB_TOKEN_TYPE: "classic"
          command:
            - pnpm
            - run
            - dockerstart
          extraHosts:
            - host.docker.internal:host-gateway
  service:
    main:
      ports:
        http:
          port: 5173
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: bolt.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - bolt.eaglepass.io
          secretName: bolt-tls-certificate
secrets:
  OPENAI_API_KEY:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "gglbmianqlel62up6isritoi5u"
    secretName: "openai-api-key"
    key: "openai-api-key"
  VITE_GITHUB_ACCESS_TOKEN:
    vault: "4uaua4a45yuhnwhehp5bwylmti"
    item: "gglbmianqlel62up6isritoi5u"
    secretName: "github-access-token"
    key: "github-access-token"
