app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/vscode-tunnel
            tag: canary
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            TUNNEL_NAME: &host "canary-tunnel"
            PROVIDER: "microsoft"
            GIT_USER_NAME: "brimdor"
            GIT_USER_EMAIL: "chrisnelsonx@gmail.com"
            DOCKER_HOST: ssh://root@10.0.50.3
            SSH_PRIVATE:
              valueFrom:
                secretKeyRef:
                  name: "ssh-keys"
                  key: "private-key"
            SSH_PUBLIC:
              valueFrom:
                secretKeyRef:
                  name: "ssh-keys"
                  key: "public-key"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      enabled: false
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 15Gi
      advancedMounts:
        main:
          main:
            - path: /home/coder
  
  defaultPodOptions:
    hostname: *host
    securityContext:
      fsGroup: 1000
    annotations:
      operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/72o4yiye3zrgz3tiucrdgjgpqq"
      operator.1password.io/item-name: "ssh-keys"