{{- if .Values.createPVs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.nfs.storageClass }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ printf "%s/data" .Values.nfs.basePath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.nfs.storageClass }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ printf "%s/config" .Values.nfs.basePath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.nfs.storageClass }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ printf "%s/mysql" .Values.nfs.basePath }}
{{- end }}
