apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.discordToken.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.discordToken.vault }}/items/{{ .Values.opSecret.discordToken.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.radarrApi.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.radarrApi.vault }}/items/{{ .Values.opSecret.radarrApi.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.sonarrApi.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.sonarrApi.vault }}/items/{{ .Values.opSecret.sonarrApi.item }}"
