- name: Install weston (Wayland compositor)
  dnf:
    name: weston
    state: present

- name: Ensure pam_systemd is enabled (for /run/user/1000 management)
  dnf:
    name: systemd-pam
    state: present

- name: Ensure '1000' has XDG_RUNTIME_DIR on boot
  lineinfile:
    path: /etc/security/pam_env.conf
    line: 'XDG_RUNTIME_DIR DEFAULT=/run/user/1000'

- name: Create weston systemd user service (run as 1000)
  copy:
    dest: /etc/systemd/system/weston-headless.service
    content: |
      [Unit]
      Description=Headless Weston Wayland compositor
      After=network.target

      [Service]
      User=admin
      Environment=XDG_RUNTIME_DIR=/run/user/1000
      ExecStart=/usr/bin/weston --backend=headless-backend.so --idle-time=0
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Enable and start weston-headless
  systemd:
    name: weston-headless
    enabled: true
    state: started