- name: Stop and disable weston-headless user service if exists
  become: true
  shell: |
    su -l admin -c 'systemctl --user stop weston-headless.service || true'
    su -l admin -c 'systemctl --user disable weston-headless.service || true'
  ignore_errors: true

- name: Remove weston-headless user service file if exists
  file:
    path: /home/admin/.config/systemd/user/weston-headless.service
    state: absent

- name: Stop and disable seatd service if exists
  systemd:
    name: seatd
    enabled: false
    state: stopped
  ignore_errors: true

- name: Remove seat group from admin if exists
  user:
    name: admin
    groups: seat
    append: no
    state: present
  ignore_errors: true

- name: Remove weston and seatd packages if installed
  package:
    name:
      - weston
      - seatd
    state: absent

- name: Install Xorg dummy driver and utilities
  package:
    name:
      - xorg-x11-server-Xorg
      - xorg-x11-drv-dummy
      - xorg-x11-xinit
    state: present

- name: Create Xorg dummy config for headless operation
  copy:
    dest: /etc/X11/xorg.conf.d/10-dummy.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      Section "Monitor"
          Identifier "Monitor0"
          HorizSync 28.0-80.0
          VertRefresh 48.0-75.0
          # 1920x1080 @ 60Hz
          Modeline "1920x1080_60.00"  172.80  1920 2040 2248 2576  1080 1083 1088 1120 -hsync +vsync
          Option "DPMS" "false"
      EndSection

      Section "Device"
          Identifier "Device0"
          Driver "dummy"
          VideoRam 256000
      EndSection

      Section "Screen"
          Identifier "Screen0"
          Device "Device0"
          Monitor "Monitor0"
          DefaultDepth 24
          SubSection "Display"
              Depth 24
              Modes "1920x1080_60.00"
          EndSubSection
      EndSection

      Section "ServerLayout"
          Identifier "Layout0"
          Screen 0 "Screen0"
      EndSection

- name: Ensure /tmp/.X11-unix exists and is writable
  file:
    path: /tmp/.X11-unix
    state: directory
    owner: root
    group: root
    mode: '1777'

- name: Set permissions on /dev/dri/card0 (if present)
  file:
    path: /dev/dri/card0
    mode: '0666'
  ignore_errors: true

- name: Set permissions on /dev/uinput (if present)
  file:
    path: /dev/uinput
    mode: '0666'
  ignore_errors: true

- name: Set permissions on all /dev/input/* (if present)
  shell: chmod 666 /dev/input/* || true
  ignore_errors: true

- name: Enable lingering for admin user (allow user systemd instance without login)
  command: loginctl enable-linger admin

- name: Start Xorg headless session as admin (optional)
  shell: |
    su -l admin -c 'Xorg :0 -config /etc/X11/xorg.conf.d/10-dummy.conf &'
  args:
    executable: /bin/bash
  ignore_errors: true