- name: Install weston (Wayland compositor)
  dnf:
    name: weston
    state: present

- name: Ensure pam_systemd is enabled (for /run/user/1000 management)
  dnf:
    name: systemd-pam
    state: present

- name: Ensure '1000' has XDG_RUNTIME_DIR on boot
  lineinfile:
    path: /etc/security/pam_env.conf
    line: 'XDG_RUNTIME_DIR DEFAULT=/run/user/1000'

- name: Ensure systemd user service directory exists for admin
  file:
    path: /home/admin/.config/systemd/user
    state: directory
    owner: 1000
    group: 1000
    mode: '0700'

- name: Create weston systemd user service (run as admin)
  copy:
    dest: /home/admin/.config/systemd/user/weston-headless.service
    owner: 1000
    group: 1000
    mode: '0644'
    content: |
      [Unit]
      Description=Weston Wayland compositor (DRM backend)
      After=network.target

      [Service]
      Environment=XDG_RUNTIME_DIR=/run/user/1000
      ExecStart=/usr/bin/weston --backend=drm-backend.so --idle-time=0
      Restart=always

      [Install]
      WantedBy=default.target

- name: Ensure /run/user/1000 exists
  file:
    path: /run/user/1000
    state: directory
    owner: 1000
    group: 1000
    mode: '0700'

- name: Set correct ownership and permissions on /run/user/1000
  file:
    path: /run/user/1000
    owner: 1000
    group: 1000
    mode: '0700'
    recurse: no

- name: Set permissions on /dev/dri/card0
  file:
    path: /dev/dri/card0
    mode: '0666'

- name: Set permissions on /dev/uinput
  file:
    path: /dev/uinput
    mode: '0666'

- name: Set permissions on all /dev/input/*
  shell: chmod 666 /dev/input/*

- name: Enable lingering for admin user (allow user systemd instance without login)
  command: loginctl enable-linger admin

- name: Start user systemd instance for admin (user@1000.service)
  command: systemctl start user@1000.service

- name: Enable and start weston-headless as user admin
  shell: |
    su -l admin -c 'XDG_RUNTIME_DIR=/run/user/1000 systemctl --user daemon-reload'
    su -l admin -c 'XDG_RUNTIME_DIR=/run/user/1000 systemctl --user enable --now weston-headless.service'