app-template:
  defaultPodOptions:
    annotations:
      operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/gsdumrejgu5tvtft4rutwtbdgy"
      operator.1password.io/item-name: "secrets"
  controllers:
    main:
      strategy: RollingUpdate
      replicas: 1
      containers:
        main:
          image:
            repository: ghcr.io/simstudioai/simstudio
            tag: latest
            pullPolicy: Always
          env:
            NODE_ENV: "production"
            NEXT_TELEMETRY_DISABLED: "1"
            NEXT_PUBLIC_APP_URL: "https://sim.eaglepass.io"
            BETTER_AUTH_URL: "https://sim.eaglepass.io"
            SOCKET_SERVER_URL: "https://sim.eaglepass.io/socket"
            NEXT_PUBLIC_SOCKET_URL: "wss://sim.eaglepass.io/socket"
            OLLAMA_URL: "http://ollama.ollama.svc.cluster.local:11434"
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-database-url"
            BETTER_AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-better-auth-secret"
            ENCRYPTION_KEY:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-encryption-key"
            INTERNAL_API_SECRET:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-internal-api-secret"
            COPILOT_API_KEY:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-copilot-api-key"
          ports:
            - name: http
              containerPort: 3000
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: "/"
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 90
                timeoutSeconds: 5
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: "/"
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 90
                timeoutSeconds: 5
                failureThreshold: 3
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      initContainers:
        migrations:
          image:
            repository: ghcr.io/simstudioai/migrations
            tag: latest
            pullPolicy: Always
          command:
            - bun
            - run
            - db:migrate
          workingDir: /app/packages/db
          env:
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-database-url"
    realtime:
      strategy: RollingUpdate
      replicas: 1
      containers:
        main:
          image:
            repository: ghcr.io/simstudioai/realtime
            tag: latest
            pullPolicy: Always
          env:
            NODE_ENV: "production"
            NEXT_PUBLIC_APP_URL: "https://sim.eaglepass.io"
            BETTER_AUTH_URL: "https://sim.eaglepass.io"
            ALLOWED_ORIGINS: "https://sim.eaglepass.io"
            SOCKET_SERVER_URL: "https://sim.eaglepass.io/socket"
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-database-url"
            BETTER_AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "sim-better-auth-secret"
          ports:
            - name: http
              containerPort: 3002
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: "/health"
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 90
                timeoutSeconds: 5
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: "/health"
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 90
                timeoutSeconds: 5
                failureThreshold: 3
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
  service:
    main:
      controller: main
      primary: true
      ports:
        http:
          port: 3000
          targetPort: http
    realtime:
      controller: realtime
      ports:
        http:
          port: 3002
          targetPort: http
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host sim.eaglepass.io
          paths:
            - path: "/"
              pathType: Prefix
              service:
                identifier: main
                port: http
            - path: "/socket"
              pathType: Prefix
              service:
                identifier: realtime
                port: http
      tls:
        - hosts:
            - *host
          secretName: sim-tls