apiVersion: v2
name: ollama
description: A Helm chart for deploying Ollama and Open WebUI using the app-template chart.
version: 1.0.0  # Increment for your releases
kubeVersion: ">=1.22.0-0" #Minimum k8s version
dependencies:
  - name: app-template
    version: 2.6.0
    repository: https://bjw-s.github.io/helm-charts
