apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-model-puller-script
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  pull-models.sh: |
{{ .Values.modelPuller.script | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-model-puller
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama-model-puller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama-model-puller
      annotations:
        checksum/config: {{ .Values.modelPuller.script | sha256sum }}
    spec:
      containers:
        - name: model-puller
          image: ollama/ollama:latest
          command: ["/bin/sh", "/scripts/pull-models.sh"]
          env:
            - name: OLLAMA_HOST
              value: "http://ollama:11434"
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      volumes:
        - name: script-volume
          configMap:
            name: ollama-model-puller-script
            defaultMode: 0755
