apiVersion: v1
kind: ConfigMap
metadata:

  name: home-assistant-custom-config
  namespace: homeassistant
data:
  custom-config.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.50.0/16