apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: woodpecker-secret
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_GITEA_CLIENT
      remoteRef:
        key: gitea.woodpecker
        property: client_id
    - secretKey: WOODPECKER_GITEA_SECRET
      remoteRef:
        key: gitea.woodpecker
        property: client_secret
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: woodpecker.agent
        property: WOODPECKER_AGENT_SECRET
    - secretKey: secret
      remoteRef:
        key: woodpecker.agent
        property: WOODPECKER_AGENT_SECRET
