apiVersion: v2
name: opencode
description: Opencode + web terminal (ttyd) (+ optional SSH) via bjw-s app-template
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts