#https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml 
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/nibble
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            NEXT_PUBLIC_API_URL: "https://ollama.eaglepass.io"
            LOG_LEVEL: "debug"
            DEBUG: "true"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      primary: true
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &Host nibble.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *Host
          secretName: nibble-tls-certificate