#https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml 
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/birdhimself/astroneer-server
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            ActiveSaveFileDescriptiveName: "broville"
            OwnerGuid: 0
            ServerName:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "server-name"
            ServerPassword:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "server-password"
            OwnerName:
              valueFrom:
                secretKeyRef:
                  name: "secrets"
                  key: "owner-name"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      type: LoadBalancer
      ports:
        http:
          nodePort: 30000
          port: 7777
          targetPort: 7777
          protocol: UDP
  # ingress:
  #   main:
  #     enabled: true
  #     className: nginx
  #     annotations:
  #       cert-manager.io/cluster-issuer: letsencrypt-prod
  #     hosts:
  #       - host: &Host astroneer.eaglepass.io
  #         paths:
  #           - path: /
  #             pathType: Prefix
  #             service:
  #               name: main
  #               port: http
  #     tls:
  #       - hosts:
  #           - *Host
  #         secretName: astroneer-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 20Gi
      advancedMounts:
        main:
          main:
            - path: ./saved
    nfs:
      type: nfs
      server: 10.0.50.3
      path: /mnt/user/astroneer
      advancedMounts:
        main:
          main:
            - path: /astrotux/AstroneerServer/Astro/Saved
  
  defaultPodOptions:
    annotations:
      operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/rfgjiop6iwlwxyefyz7cqjli2u"
      operator.1password.io/item-name: "secrets"