apiVersion: v2
name: openwebui
description: A Helm chart for deploying Open WebUI using bjw-s app-template
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts