# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Tailscale
- name: tailscale-auth-key
  data:
    - key: authkey
      prefix: tskey-auth-
      length: 48
      special: false

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true
