app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/surajverma/homehub
            tag: latest
            pullPolicy: IfNotPresent
          env:
            TZ: "America/Chicago"
          # envFrom:
          #   - secretRef:
          #       name: homehub-secrets
          ports:
            - name: http
              containerPort: 5000
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 10
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: http
                initialDelaySeconds: 15
                periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
  service:
    main:
      controller: main
      primary: true
      ports:
        http:
          port: 5000
          targetPort: http
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host homehub.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homehub-tls-certificate
  persistence:
    data:
      enabled: true
      type: emptyDir
      advancedMounts:
        main:
          main:
            - path: /app/data
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000