apiVersion: v2
name: second-brain-canary
description: A Helm chart for deploying Second Brain canary
type: application
version: 0.1.3
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
