---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  labels:
    app: "{{ .Values.app.name }}"
    app.kubernetes.io/name: "{{ .Values.app.name }}"
    app.kubernetes.io/instance: "{{ .Values.app.name }}"
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: "{{ .Values.service.port }}"
      targetPort: http
      protocol: TCP
  selector:
    app: "{{ .Values.app.name }}"