apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.OPENAI_API_KEY.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.OPENAI_API_KEY.vault }}/items/{{ .Values.opSecret.OPENAI_API_KEY.item }}"