apiVersion: v1
kind: Service
metadata:
  name: n8n-db
  labels:
    app: n8n-db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: n8n-db
