apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.OPENAI_API_KEY.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.OPENAI_API_KEY.vault }}/items/{{ .Values.secrets.OPENAI_API_KEY.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.VITE_GITHUB_ACCESS_TOKEN.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.VITE_GITHUB_ACCESS_TOKEN.vault }}/items/{{ .Values.secrets.VITE_GITHUB_ACCESS_TOKEN.item }}"