apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecrets.SSH_KEYS.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecrets.SSH_KEYS.vault }}/items/{{ .Values.opSecrets.SSH_KEYS.item }}"