apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.PASSWORD.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.PASSWORD.vault }}/items/{{ .Values.secrets.PASSWORD.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.SUDO_PASSWORD.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.SUDO_PASSWORD.vault }}/items/{{ .Values.secrets.SUDO_PASSWORD.item }}"