apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.SSH_PRIVATE.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.SSH_PRIVATE.vault }}/items/{{ .Values.secrets.SSH_PRIVATE.item }}"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.SSH_PUBLIC.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.SSH_PUBLIC.vault }}/items/{{ .Values.secrets.SSH_PUBLIC.item }}"