apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  namespace: "{{ .Values.app.name }}"
  annotations:
    group: production
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: "{{ .Values.pvc.storageSize }}"