apiVersion: v2
name: bytebot
description: Bytebot deployment for the homelab using the bjw-s app-template.
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.2.0
    repository: https://bjw-s-labs.github.io/helm-charts