app-template:
  global:
    nameOverride: bytebot

  controllers:
    main:
      replicas: 1
      containers:
        main:
          image:
            repository: docker.io/bytebotai/bytebot
            tag: latest
            pullPolicy: Always
          env:
            NEXTAUTH_URL: https://bytebot.eaglepass.io
            BYTEBOT_PUBLIC_URL: https://bytebot.eaglepass.io
            BYTEBOT_ENABLE_SIGNUP: "false"
            BYTEBOT_LLM_PROVIDER: ollama
            OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
            BYTEBOT_DEFAULT_MODEL: llama3
            BYTEBOT_AGENT_URL: http://bytebot-agent.bytebot.svc.cluster.local:7000
            BYTEBOT_DESKTOP_URL: http://bytebot-desktop.bytebot.svc.cluster.local:7681
            DATABASE_URL: postgresql://bytebot:bytebot-dev@bytebot-postgresql.bytebot.svc.cluster.local:5432/bytebot
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - name: http
              containerPort: 3000

    agent:
      replicas: 1
      containers:
        agent:
          image:
            repository: ghcr.io/bytebot-ai/bytebot-agent
            tag: latest
            pullPolicy: Always
          env:
            BYTEBOT_AGENT_HOST: 0.0.0.0
            BYTEBOT_AGENT_PORT: "7000"
            BYTEBOT_LLM_PROVIDER: ollama
            OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
            BYTEBOT_DEFAULT_MODEL: llama3
            DATABASE_URL: postgresql://bytebot:bytebot-dev@bytebot-postgresql.bytebot.svc.cluster.local:5432/bytebot
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 7000

    desktop:
      replicas: 1
      containers:
        desktop:
          image:
            repository: ghcr.io/bytebot-ai/bytebot-desktop
            tag: latest
            pullPolicy: Always
          env:
            BYTEBOT_DESKTOP_HOST: 0.0.0.0
            BYTEBOT_DESKTOP_PORT: "7681"
            BYTEBOT_AGENT_URL: http://bytebot-agent.bytebot.svc.cluster.local:7000
            BYTEBOT_LLM_PROVIDER: ollama
            OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
            BYTEBOT_DEFAULT_MODEL: llama3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 7681

    postgresql:
      type: statefulset
      replicas: 1
      containers:
        postgresql:
          image:
            repository: docker.io/library/postgres
            tag: "16"
            pullPolicy: IfNotPresent
          env:
            POSTGRES_DB: bytebot
            POSTGRES_USER: bytebot
            POSTGRES_PASSWORD: bytebot-dev
            PGDATA: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - name: postgres
              containerPort: 5432

  service:
    main:
      enabled: true
      controller: main
      ports:
        http:
          port: 3000
          targetPort: http
    agent:
      enabled: true
      controller: agent
      ports:
        http:
          port: 7000
          targetPort: http
    desktop:
      enabled: true
      controller: desktop
      ports:
        http:
          port: 7681
          targetPort: http
    postgresql:
      enabled: true
      controller: postgresql
      ports:
        postgres:
          port: 5432
          targetPort: postgres

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: bytebot.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - bytebot.eaglepass.io
          secretName: bytebot-tls

  persistence:
    postgresql-data:
      type: emptyDir
      advancedMounts:
        postgresql:
          postgresql:
            - path: /var/lib/postgresql/data