app-template:
  global:
    nameOverride: bytebot

  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/bytebot-ai/bytebot
            tag: latest
            pullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            NEXTAUTH_URL: https://bytebot.eaglepass.io
            BYTEBOT_PUBLIC_URL: https://bytebot.eaglepass.io
            BYTEBOT_ENABLE_SIGNUP: "false"
            BYTEBOT_LLM_PROVIDER: ollama
            OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
            BYTEBOT_DEFAULT_MODEL: llama3
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

  service:
    main:
      controller: main
      ports:
        http:
          port: 3000

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host bytebot.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: bytebot-tls

  persistence: {}