bytebot:
  replicaCount: 1
  image:
    repository: docker.io/bytebotai/bytebot
    tag: latest
    pullPolicy: Always
  env:
    NEXTAUTH_URL: https://bytebot.eaglepass.io
    BYTEBOT_PUBLIC_URL: https://bytebot.eaglepass.io
    BYTEBOT_ENABLE_SIGNUP: "false"
    BYTEBOT_LLM_PROVIDER: ollama
    OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
    BYTEBOT_DEFAULT_MODEL: gpt-oss:20b
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: bytebot.eaglepass.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - bytebot.eaglepass.io
        secretName: bytebot-tls
  persistence:
    enabled: false