apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "emby.fullname" . }}-config
  labels:
    app: {{ include "emby.name" . }}
    chart: {{ include "emby.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
