apiVersion: v1
kind: Service
metadata:
  name: {{ include "emby.fullname" . }}
  labels:
    app: {{ include "emby.name" . }}
    chart: {{ include "emby.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8920
      targetPort: 8096
      protocol: TCP
    - name: http2
      port: 8096
      targetPort: 8920
      protocol: TCP
  selector:
    app: {{ include "emby.name" . }}
    release: {{ .Release.Name }}
