apiVersion: v1
kind: Service
metadata:
  name: {{ include "emby.fullname" . }}
  labels:
    app: {{ include "emby.name" . }}
    chart: {{ include "emby.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    app: {{ include "emby.name" . }}
    release: {{ .Release.Name }}
