apiVersion: v2
name: family-games-rules
description: A Helm chart for deploying Family Games Rules using bjw-s app-template
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
