apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "open-webui" "persistence" "existingClaim" | default "openwebui-cephfs-pvc" }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard-rwx"
  resources:
    requests:
      storage: {{ index .Values "open-webui" "persistence" "size" | default "100Gi" }}
