apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values "open-webui" "persistence" "existingClaim" | default "openwebui-nfs-pvc" }}
spec:
  capacity:
    storage: {{ index .Values "open-webui" "persistence" "size" | default "100Gi" }}
  accessModes:
    {{- range (index .Values "open-webui" "persistence" "accessModes") }}
    - {{ . }}
    {{- end }}
  nfs:
    server: {{ index .Values "open-webui" "nfs" "server" | quote }}
    path: {{ index .Values "open-webui" "nfs" "path" | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "open-webui" "persistence" "existingClaim" | default "openwebui-nfs-pvc" }}
spec:
  accessModes:
    {{- range (index .Values "open-webui" "persistence" "accessModes") }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ index .Values "open-webui" "persistence" "size" | default "100Gi" }}
  volumeName: {{ index .Values "open-webui" "persistence" "existingClaim" | default "openwebui-nfs-pvc" }}
