apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-nfs-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.50.3
    path: /mnt/user/openwebui
