open-webui:
  ollama:
    enabled: false
  # Point OWUI at your external Ollama
  ollamaUrls:
    - "http://ollama.ollama.svc.cluster.local:11434"

  pipelines:
    enabled: true

  ingress:
    enabled: true
    class: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.eaglepass.io"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: &openwebuihost ai.eaglepass.io
    tls: true

  # Import all sensitive env from a Secret (chart-supported)
  extraEnvFrom:
    - secretRef:
        name: secrets

  # Non-secret env stays in extraEnvVars
  extraEnvVars:
    - name: ENABLE_LOGIN_FORM
      value: "true"
    - name: WEBUI_URL
      value: *openwebuihost
    - name: BYPASS_MODEL_ACCESS_CONTROL
      value: "false"
    - name: OLLAMA_BASE_URL
      value: "http://ollama.ollama.svc.cluster.local:11434"
    # RAG embeddings via Ollama endpoint
    - name: RAG_EMBEDDING_ENGINE
      value: "ollama"
    - name: RAG_OLLAMA_BASE_URL
      value: "http://ollama.ollama.svc.cluster.local:11434"
    # OpenAI STT uses OPENAI_API_KEY from the Secret
    - name: AUDIO_STT_ENGINE
      value: "openai"
    # MCPO integration
    - name: MCPO_URL
      value: "http://mcpo.open-webui.svc.cluster.local:8081"

  podAnnotations:
    operator.1password.io/auto-restart: "true"
    operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/gsdumrejgu5tvtft4rutwtbdgy"
    operator.1password.io/item-name: "secrets"

  extraResources:
    # Secret synced by 1Password Operator; values overwritten by the operator
    - apiVersion: v1
      kind: Secret
      metadata:
        name: secrets
        annotations:
          operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/gsdumrejgu5tvtft4rutwtbdgy"
          operator.1password.io/item-name: "secrets"
      type: Opaque
      stringData:
        # keys must match env names consumed via extraEnvFrom
        WEBUI_SECRET_KEY: "placeholder"
        OPENAI_API_KEY: "placeholder"
        MCPO_API_KEY: "placeholder"

    # mcpo Service (internal)
    - apiVersion: v1
      kind: Service
      metadata:
        name: mcpo
        labels: { app.kubernetes.io/name: mcpo }
      spec:
        type: ClusterIP
        selector: { app.kubernetes.io/name: mcpo }
        ports:
          - name: http
            port: 8081
            targetPort: 8081

    # mcpo Deployment with git-sync sidecar
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mcpo
        labels: { app.kubernetes.io/name: mcpo }
      spec:
        replicas: 1
        selector:
          matchLabels: { app.kubernetes.io/name: mcpo }
        template:
          metadata:
            labels: { app.kubernetes.io/name: mcpo }
          spec:
            securityContext:
              runAsNonRoot: false
            initContainers:
              - name: wait-mcpo-secret
                image: busybox:1.36
                command: ["/bin/sh","-c"]
                args:
                  - |
                    set -eu
                    FILE=/var/secret/MCPO_API_KEY
                    for i in $(seq 1 120); do
                      if [ -f "$FILE" ] && [ -s "$FILE" ] && [ "$(cat "$FILE")" != "placeholder" ]; then
                        exit 0
                      fi
                      sleep 5
                    done
                    echo "MCPO_API_KEY not populated" >&2; exit 1
                volumeMounts:
                  - name: mcpo-secret
                    mountPath: /var/secret
            containers:
              - name: mcpo
                image: ghcr.io/open-webui/mcpo:main
                imagePullPolicy: Always
                args: ["--config","/config/repo/config.json","--host","0.0.0.0","--port","8081","--hot-reload"]
                ports: [{ name: http, containerPort: 8081 }]
                envFrom:
                  - secretRef: { name: secrets }
                volumeMounts:
                  - name: mcpo-config
                    mountPath: /config
                readinessProbe:
                  httpGet: { path: /health, port: 8081 }
                  initialDelaySeconds: 5
                  periodSeconds: 10
              - name: git-sync
                image: registry.k8s.io/git-sync/git-sync:v4.5.0
                env:
                  - { name: GITSYNC_REPO,   value: "https://github.com/brimdor/mcp-servers" }
                  - { name: GITSYNC_BRANCH, value: "main" }
                  - { name: GITSYNC_ROOT,   value: "/config" }
                  - { name: GITSYNC_LINK,   value: "repo" }
                  - { name: GITSYNC_PERIOD, value: "30s" }
                  - { name: GITSYNC_ONE_TIME, value: "false" }
                volumeMounts:
                  - name: mcpo-config
                    mountPath: /config
            volumes:
              - name: mcpo-config
                emptyDir: {}
              - name: mcpo-secret
                secret:
                  secretName: secrets
                  optional: true
                  items:
                    - key: MCPO_API_KEY
                      path: MCPO_API_KEY

  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "latest"
    pullPolicy: "Always"

  persistence:
    enabled: true
    existingClaim: openwebui-nfs-pvc
    additionalVolumes:
      - name: embedded-models
        persistentVolumeClaim: { claimName: openwebui-embedded-models-pvc }
      - name: openwebui-data
        persistentVolumeClaim: { claimName: openwebui-data-pvc }
    additionalVolumeMounts:
      - { name: embedded-models, mountPath: /app/embedded-models }
      - { name: openwebui-data, mountPath: /app/backend/data }
