# values.yaml for bolt-diy Helm chart using bjw-s common chart
# See https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml for all options
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brimdor/bolt
            tag: canary
            pullPolicy: Always
          env:
            NODE_ENV: production
            COMPOSE_PROFILES: production
            PORT: 5173
            VITE_GITHUB_TOKEN_TYPE: "classic"
            RUNNING_IN_DOCKER: "true"
            VITE_LOG_LEVEL: "info"
            DEFAULT_NUM_CTX: "20000"
            OLLAMA_API_BASE_URL: "http://ollama.ollama.svc.cluster.local:11434"
            OPENAI_API_KEY:
              valueFrom:
                  secretKeyRef:
                    name: "secrets"
                    key: "openai-api-key"
            VITE_GITHUB_ACCESS_TOKEN:
              valueFrom:
                  secretKeyRef:
                    name: "secrets"
                    key: "github-access-token"

          command:
            - pnpm
            - run
            - dockerstart
          extraHosts:
            - host.docker.internal:host-gateway
  service:
    main:
      ports:
        http:
          port: 5173
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: bolt.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - bolt.eaglepass.io
          secretName: bolt-tls-certificate
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
    annotations:
      operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/gglbmianqlel62up6isritoi5u"
      operator.1password.io/item-name: "secrets"